export const TIMING = {
  EDITOR_SETUP_DELAY: 25,
  HIDE_PROPS_DELAY: 100,
  SETTINGS_UPDATE_DELAY: 100,
  UPDATE_DEBOUNCE: 500,
  METADATA_CHANGE_DEBOUNCE: 500,
  SETTINGS_FILE_DEBOUNCE: 500,
  FORCED_UPDATE_THROTTLE: 1000,
  USER_INACTIVITY_THRESHOLD: 1000,
} as const;
