/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MirrorUIPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/view.ts
var import_obsidian = require("obsidian");
var MIRROR_UI_VIEW_TYPE = "mirror-ui-view";
var MirrorUIView = class extends import_obsidian.ItemView {
  getViewType() {
    return "mirror-ui-view";
  }
  getDisplayText() {
    return "Mirror UI Title - Emergency Contact";
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h1", { text: "Emergeny contact" });
    new import_obsidian.Setting(contentEl).setName("Ghostbusters").addButton((item) => {
      item.setButtonText("Call");
    });
  }
};

// src/main.ts
var DEFALT_SETTINGS = {
  myPluginName: "\u{1F440} Mirror Preview Plugin"
};
var MirrorUIPlugin = class extends import_obsidian2.Plugin {
  //app: App;
  // Útil para quando você vai trabalhar com dados padrão e dados do usuários salvos nas configurações
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFALT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    this.saveData(this.settings);
  }
  async onload() {
    console.log("[Mirror Notes] v6 loaded \u2014 MirrorUIPlugin class born");
    this.registerEvent(
      this.app.workspace.on("file-open", this.addToolbar.bind(this))
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", this.addToolbar.bind(this))
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", this.addToolbar.bind(this))
    );
    await this.loadSettings();
    this.registerView(MIRROR_UI_VIEW_TYPE, (leaf) => new MirrorUIView(leaf));
    new import_obsidian2.Notice("Opening " + this.settings.myPluginName + "!");
    this.addRibbonIcon("eye", this.settings.myPluginName, () => {
      new import_obsidian2.Notice("Triggering " + this.settings.myPluginName + ".");
    });
    this.addRibbonIcon("file", this.settings.myPluginName, () => {
      this.openView();
    });
    this.addCommand(
      {
        id: "decorate",
        name: "Decorate Titles",
        editorCallback: (editor) => {
          const value = editor.getValue().replace(/^\#(.*)$/gm, (match) => match + " \u{1F600}");
          editor.setValue(value);
          new import_obsidian2.Notice(value);
        }
      }
    );
    this.addCommand(
      {
        id: "Peek",
        name: "Peek into the dark",
        checkCallback: (checking) => {
          const isPastDark = new Date().getHours() >= 23;
          if (isPastDark) {
            if (!checking) {
              new import_obsidian2.Notice("Booo!");
            }
            return true;
          }
          return false;
        }
      }
    );
  }
  async onunload() {
    new import_obsidian2.Notice("Closing Mirror Preview Plugin!");
  }
  openView() {
    this.app.workspace.detachLeavesOfType(MIRROR_UI_VIEW_TYPE);
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf)
      leaf.setViewState({
        type: MIRROR_UI_VIEW_TYPE
      });
  }
  async addToolbar(leaf) {
    var _a;
    if (!leaf || !leaf.view || !(leaf.view instanceof import_obsidian2.MarkdownView))
      return;
    const activeLeaf = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (!activeLeaf)
      return;
    const view = leaf.view;
    const file = view.file;
    if (!file)
      return;
    const frontmatter = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    if ((frontmatter == null ? void 0 : frontmatter.type) === "project") {
      const toolbar = activeDocument.createElement("div");
      let embedBlock = toolbar.createEl("h1", { text: "MARLON" });
      toolbar.className = "project-toolbar";
      this.removeToolbar();
      let currentView = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
      let corpodocs = document.querySelector(".metadata-container");
      if (corpodocs) {
        new import_obsidian2.Notice("AHA");
        let conteudo = await this.app.vault.adapter.read("templates/ui-live_preview-mode.md");
        let file2 = this.app.vault.getAbstractFileByPath("templates/ui-live_preview-mode.md");
        if (file2 instanceof import_obsidian2.TFile) {
          let conteudo2 = this.app.vault.read(file2);
        } else {
        }
      }
    } else {
      this.removeToolbar();
    }
  }
  removeToolbar() {
    const existingToolbar = document.querySelector(".project-toolbar");
    if (existingToolbar)
      existingToolbar.remove();
  }
};
