/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ProjectToolbarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var ProjectToolbarPlugin = class extends import_obsidian.Plugin {
  onload() {
    console.log("[Mirror Notes] v4 loaded \u2014 ProjectToolbarPlugin + MarkdownRenderer");
    this.registerEvent(
      this.app.workspace.on("file-open", this.addToolbar.bind(this))
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", this.addToolbar.bind(this))
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", this.addToolbar.bind(this))
    );
  }
  async addToolbar(leaf) {
    var _a;
    if (!leaf || !leaf.view || !(leaf.view instanceof import_obsidian.MarkdownView))
      return;
    const activeLeaf = this.app.workspace.activeLeaf;
    if (!activeLeaf)
      return;
    const view = leaf.view;
    const file = view.file;
    if (!file)
      return;
    const frontmatter = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    if ((frontmatter == null ? void 0 : frontmatter.type) === "project") {
      const toolbar = activeDocument.createElement("div");
      toolbar.className = "project-toolbar";
      document.body.appendChild(toolbar);
      this.removeToolbar();
      activeLeaf.view.containerEl.prepend(toolbar);
      new import_obsidian.Notice("AHA");
      let marlon = "marlon\n leticia \n livia";
      import_obsidian.MarkdownRenderer.render(this.app, marlon, toolbar, "templates/ui-live_preview-mode.md", this);
    } else {
      this.removeToolbar();
    }
  }
  removeToolbar() {
    const existingToolbar = document.querySelector(".project-toolbar");
    if (existingToolbar)
      existingToolbar.remove();
  }
};
