/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var MyPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.toolbarEl = null;
  }
  onload() {
    console.log("[Mirror Notes] v2 loaded \u2014 Ribbon button + tooltip");
    this.addToolbar();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", this.onActiveLeafChange.bind(this))
    );
  }
  addToolbar() {
    this.toolbarEl = document.querySelector(".workspace-ribbon-left");
    if (!this.toolbarEl)
      return;
    this.addToolbarIcon();
  }
  addToolbarIcon() {
    if (!this.toolbarEl)
      return;
    const button = this.addIcon("Custom Tool", "Click me", "mdi-information-variant");
    button.addEventListener("click", () => {
      this.insertCustomBlock();
    });
    this.toolbarEl.appendChild(button);
  }
  insertCustomBlock() {
    const activeLeaf = this.app.workspace.activeLeaf;
    if (!activeLeaf || !activeLeaf.view)
      return;
    const view = activeLeaf.view;
    if (!(view instanceof import_obsidian.MarkdownView))
      return;
    const markdownView = view;
    const file = markdownView.file;
    if (!file)
      return;
    const container = markdownView.containerEl.querySelector(".markdown-preview-view") || markdownView.containerEl.querySelector(".markdown-source-view");
    if (container && !container.querySelector(".custom-block")) {
      const customBlock = document.createElement("div");
      customBlock.className = "custom-block";
      customBlock.innerText = "MARLON BRANDON";
      const header = container.querySelector("h1");
      if (header && header.parentElement) {
        header.parentElement.insertBefore(customBlock, header.nextSibling);
      } else {
        container.appendChild(customBlock);
      }
    }
  }
  onActiveLeafChange() {
    if (this.toolbarEl) {
      this.toolbarEl.innerHTML = "";
      this.addToolbarIcon();
    }
  }
  addIcon(label, tooltip, icon) {
    const button = document.createElement("div");
    button.className = "toolbar-icon";
    button.innerHTML = `<span class="mdi ${icon}" aria-hidden="true"></span>`;
    button.setAttribute("aria-label", tooltip);
    button.setAttribute("title", tooltip);
    button.setAttribute("role", "button");
    button.setAttribute("aria-haspopup", "true");
    button.setAttribute("aria-expanded", "false");
    button.appendChild(document.createTextNode(label));
    this.addHoverTooltip(button, label);
    return button;
  }
  addHoverTooltip(el, text) {
    const tooltip = this.createTooltip(text);
    el.addEventListener("mouseenter", () => {
      tooltip.style.display = "block";
    });
    el.addEventListener("mouseleave", () => {
      tooltip.style.display = "none";
    });
  }
  createTooltip(text) {
    const tooltip = document.createElement("div");
    tooltip.className = "tooltip";
    tooltip.style.display = "none";
    tooltip.innerText = text;
    document.body.appendChild(tooltip);
    return tooltip;
  }
};
