/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var MyPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("[Mirror Notes] v1 loaded \u2014 Skeleton: Notice, stubs");
    new import_obsidian.Notice("Opening \u{1F440} Mirror Preview Plugin!");
  }
  async onunload() {
    this.registerEvent(
      new import_obsidian.Notice("Closing Mirror Preview Plugin!")
      //this.app.workspace.on('active-leaf-change', this.onFileOpen.bind(this))
    );
  }
  async onFileOpen(leaf) {
    if (!leaf || !leaf.view || !(leaf.view instanceof import_obsidian.MarkdownView))
      return;
    const view = leaf.view;
    const file = view.file;
    if (!file)
      return;
    const fileCache = this.app.metadataCache.getFileCache(file);
    if (fileCache && fileCache.frontmatter && fileCache.frontmatter.type === "project") {
      this.insertCustomBlock(view);
    }
  }
  async insertCustomBlock(view) {
    new import_obsidian.Notice("RODOU!");
    const container = view.containerEl.querySelector(".markdown-preview-view") || view.containerEl.querySelector(".markdown-source-view");
    if (container && !container.querySelector(".custom-block")) {
      const content = "MARLON BRANDON";
      const customBlock = document.createElement("div");
      customBlock.className = "custom-block";
      customBlock.innerHTML = content;
      container.appendChild(customBlock);
    }
  }
};
