/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var u=Object.defineProperty;var E=Object.getOwnPropertyDescriptor;var x=Object.getOwnPropertyNames;var S=Object.prototype.hasOwnProperty;var M=(r,e)=>{for(var t in e)u(r,t,{get:e[t],enumerable:!0})},b=(r,e,t,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of x(e))!S.call(r,o)&&o!==t&&u(r,o,{get:()=>e[o],enumerable:!(i=E(e,o))||i.enumerable});return r};var k=r=>b(u({},"__esModule",{value:!0}),r);var T={};M(T,{default:()=>h,toggleWidgetEffect:()=>a});module.exports=k(T);var s=require("obsidian"),y=require("@codemirror/state");var l=require("@codemirror/state"),C=l.StateEffect.define(),a=l.StateEffect.define(),d=l.StateField.define({create(r){return{enabled:!1,templatePath:"templates/test-template.md",frontmatter:g(r.doc.toString())}},update(r,e){if(e.docChanged){let t=g(e.state.doc.toString());if(JSON.stringify(t)!==JSON.stringify(r.frontmatter))return{...r,frontmatter:t}}for(let t of e.effects){if(t.is(C))return{...r,templatePath:t.value.templatePath};if(t.is(a))return{...r,enabled:t.value}}return r}});function g(r){let e=r.match(/^---\n([\s\S]*?)\n---/);if(!e)return{};try{let t=e[1],i={};return t.split(`
`).forEach(o=>{let[c,n]=o.split(":").map(p=>p.trim());c&&n&&(i[c]=n.replace(/^["']|["']$/g,""))}),i}catch(t){return{}}}var v=require("@codemirror/view"),m=require("obsidian");function w(r){return v.ViewPlugin.fromClass(class{constructor(e){this.view=e;this.container=null;this.currentState=null;setTimeout(()=>this.updateWidget(),100)}update(e){let t=e.state.field(d,!1);JSON.stringify(this.currentState)!==JSON.stringify(t)&&(this.currentState=t,this.updateWidget())}updateWidget(){var t;let e=this.view.state.field(d,!1);if(!(e!=null&&e.enabled)||!e.templatePath||((t=e.frontmatter)==null?void 0:t.type)!=="project"){this.removeWidget();return}this.container||this.createWidget(),this.renderContent(e)}createWidget(){this.removeWidget(),this.container=document.createElement("div"),this.container.className="mirror-ui-widget",this.container.style.cssText=`
          background: var(--background-secondary);
          border: 1px solid var(--background-modifier-border);
          border-radius: 6px;
          padding: 15px;
          margin-bottom: 15px;
          position: relative;
          min-height: 80px;
        `;let e=this.view.dom,t=e.parentElement;t&&t.insertBefore(this.container,e)}async renderContent(e){if(this.container){this.container.innerHTML=`
          <div style="opacity: 0.5;">Loading template...</div>
        `;try{let t=r.app.vault.getAbstractFileByPath(e.templatePath);if(!t||!(t instanceof m.TFile)){this.container.innerHTML=`
              <div style="color: var(--text-error);">
                Template not found: ${e.templatePath}
              </div>
            `;return}let o=(await r.app.vault.read(t)).replace(/\{\{(\w+)\}\}/g,(p,f)=>e.frontmatter[f]||p);this.container.innerHTML="";let c=document.createElement("div");this.container.appendChild(c);let n=r.app.workspace.getActiveFile();n&&await m.MarkdownRenderer.renderMarkdown(o,c,n.path,r),this.addCloseButton()}catch(t){console.error("Error rendering template:",t),this.container.innerHTML=`
            <div style="color: var(--text-error);">
              Error: ${t}
            </div>
          `}}}addCloseButton(){if(!this.container)return;let e=document.createElement("button");e.textContent="\xD7",e.style.cssText=`
          position: absolute;
          top: 10px;
          right: 10px;
          background: none;
          border: none;
          font-size: 20px;
          cursor: pointer;
          opacity: 0.5;
          padding: 5px 10px;
          line-height: 1;
        `,e.onmouseover=()=>{e.style.opacity="1"},e.onmouseout=()=>{e.style.opacity="0.5"},e.onclick=()=>{this.view.dispatch({effects:a.of(!1)})},this.container.appendChild(e)}removeWidget(){this.container&&(this.container.remove(),this.container=null)}destroy(){this.removeWidget()}})}var h=class extends s.Plugin{constructor(){super(...arguments);this.activeEditors=new Map}async onload(){console.log("[Mirror Notes] v20 loaded \u2014 CM6 integration"),this.registerEvent(this.app.workspace.on("editor-change",(t,i)=>{i instanceof s.MarkdownView&&i.file&&this.setupEditor(i)})),this.registerEvent(this.app.workspace.on("file-open",t=>{t&&setTimeout(()=>{let i=this.app.workspace.getActiveViewOfType(s.MarkdownView);i&&this.setupEditor(i)},50)})),this.registerEvent(this.app.workspace.on("active-leaf-change",t=>{(t==null?void 0:t.view)instanceof s.MarkdownView&&setTimeout(()=>{this.setupEditor(t.view)},50)})),this.app.workspace.iterateAllLeaves(t=>{t.view instanceof s.MarkdownView&&t.view.file&&this.setupEditor(t.view)})}setupEditor(t){var f;let i=t.file;if(!i)return;let o=t.editor.cm;if(!o)return;o.state.field(d,!1)||(console.log("Adding extensions to editor for:",i.path),o.dispatch({effects:y.StateEffect.appendConfig.of([d,w(this)])}));let n=this.app.metadataCache.getFileCache(i),p=((f=n==null?void 0:n.frontmatter)==null?void 0:f.type)==="project";o.dispatch({effects:a.of(p)})}onunload(){this.activeEditors.clear()}};
